#!/usr/bin/env python

import sys

if len(sys.argv) < 2:
   sys.stderr.write("Usage: %s file1 [ file2 ... ]\n" % sys.argv[0])
   sys.exit(1)

import quippy
all_at=[]
i=0
for f in sys.argv[1:]:
   sys.stderr.write("%s\n" %  f)
   al = quippy.AtomsReader(f)
   for at in al:
      all_at.append(at)
      i += 1
      if i%1000 == 0:
	 sys.stderr.write(".")

sys.stderr.write("\n")

print "# i E E-KE V"
all_at.sort(key = lambda at: -at.info['ns_energy'])
i=0
for at in all_at:
   print i, at.info['ns_energy'], at.info['ns_energy']-at.get_kinetic_energy(), at.get_volume()
   i += 1
