#!/usr/bin/env python

import pstats, sys

if len(sys.argv) != 2:
   sys.stderr.write("Usage: %s stats_file\n" % sys.argv[0])
   sys.exit(1)

import pstats
p = pstats.Stats(sys.argv[1])
print "BASIC STATS"
p.sort_stats('cumulative').print_stats()
print ""
print "CALLERS"
p.sort_stats('cumulative').print_callers()
print ""
print "CALLEES"
p.sort_stats('cumulative').print_callees()
