#!/bin/bash

mydir=`dirname $0`

nf=`ls test*cluster*energies | wc -l`
if [ $nf != 0 ]; then
   for f in test*cluster*energies; do
      root=${f/.energies/}
      if [[ ! -s $f.analysis || $f -nt $f.analysis ]]; then
	 echo analyze $f
	 $mydir/../ns_analyse -M 0.002 -D 0.002 -n 99 -k 1.0 $f > $f.analysis
      fi
   done
fi

nf=`ls test*periodic*energies | wc -l`
if [ $nf != 0 ]; then
   for f in test*periodic*energies; do
      root=${f/.energies/}
      if [[ ! -s $f.analysis || $f -nt $f.analysis ]]; then
	 echo analyze $f
	 $mydir/../ns_analyse  -M 0.0020 -D 0.0015625 -n 400 -k 1.0 $f > $f.analysis
	 root=${f/.energies/}
	 $mydir/../ns_process_traj ${root}.traj*xyz > $root.proc_traj
      fi
   done
fi
