#!/bin/bash
#CCMS nprocs=16:network=any:big32
#PBS -l walltime=16:00:00
#PBS -N test.cluster.MD
#PBS -o test.cluster.MD.stdout
#PBS -e test.cluster.MD.stderr
#PBS -S /bin/bash

cd $PBS_O_WORKDIR
startdir=$PWD

if [ -f $HOME/.bashrc ]; then
   . $HOME/.bashrc
fi

export WORK_DIR=$WORKDIR/$JOB_ID

echo Running in `pwd` >> $startdir/test.cluster.MD.stdout.rundir
echo Running on `hostname` >> $startdir/test.cluster.MD.stdout.rundir

mpirun  ../ns_run < inputs.test.cluster.MD > test.cluster.MD.out
