#!/bin/bash
#CCMS nprocs=32:network=fast:n2013
#PBS -l walltime=16:00:00
#PBS -N test.periodic.MC
#PBS -o test.periodic.MC.stdout
#PBS -e test.periodic.MC.stderr
#PBS -S /bin/bash

cd $PBS_O_WORKDIR
startdir=$PWD

if [ -f $HOME/.bashrc ]; then
   . $HOME/.bashrc
fi

export WORK_DIR=$WORKDIR/$JOB_ID

echo Running in `pwd` >> $startdir/test.periodic.MC.stdout.rundir
echo Running on `hostname` >> $startdir/test.periodic.MC.stdout.rundir

mpirun  ../ns_run < inputs.test.periodic.MC > test.periodic.MC.out
