#!/bin/bash
#CCMS nprocs=32:network=fast:big32
#PBS -l walltime=16:00:00
#PBS -N test.periodic.MC_velo
#PBS -o test.periodic.MC_velo.stdout
#PBS -e test.periodic.MC_velo.stderr
#PBS -S /bin/bash

cd $PBS_O_WORKDIR
startdir=$PWD

if [ -f $HOME/.bashrc ]; then
   . $HOME/.bashrc
fi

export WORK_DIR=$WORKDIR/$JOB_ID

echo Running in `pwd` >> $startdir/test.periodic.MC_velo.stdout.rundir
echo Running on `hostname` >> $startdir/test.periodic.MC_velo.stdout.rundir

mpirun  ../ns_run < inputs.test.periodic.MC_velo > test.periodic.MC_velo.out
