#!/bin/bash

mydir=`dirname $0`

nd=`ls run*cluster* | wc -l`
if [ $nd != 0 ]; then
   for d in run*cluster*; do
      do=0
      for f in $d/*energies; do
	 if [ ! -s $f ]; then
	    do=1
	 fi
      done
      last_energy=`ls -tr $d/*energies | tail -1`
      if [ $last_energy -nt analysis.$d ]; then
	 do=1
      fi
      if [ $do == 1 ]; then
	 echo analyze $f
	 $mydir/../ns_analyse -M 0.002 -D 0.002 -n 99 -k 1.0 $d/*energies > analysis.$d
      fi
   done
fi

nd=`ls run*periodic* | wc -l`
if [ $nd != 0 ]; then
   for d in run*periodic*; do
      do=0
      for f in $d/*energies; do
	 if [ ! -s $f ]; then
	    do=1
	 fi
      done
      last_energy=`ls -tr $d/*energies | tail -1`
      if [ $last_energy -nt analysis.$d ]; then
	 do=1
      fi
      if [ $do == 1 ]; then
	 echo analyze $f
	 $mydir/../ns_analyse -M 0.002 -D 0.0015625 -n 400 -k 1.0 $d/*energies > analysis.$d
	 $mydir/../ns_process_traj $d/*.traj*xyz > proc_traj.$d
      fi
   done
fi
